### ISSUE TITLE
failed to write: bad file descriptor.

### ISSUE THREAD

**Issue by ranasikandar** [droe/sslsplit#106] opened 2015-09-01 10:22 UTC
I'm sorry if it's a stupid question as I'm just newbie in Linux. I'm using Kali Linux 32bit and builtin sslsplit. Which is state of the art no doubt. I'm trying to capture Facebook packets from my android device, connected to wlan, using sslsplit. I think I did everything according to tutorials on internet, but I'm unable to capture FB packet in my specified directory nor in root dir even USB storage didn't work. The every code I entered in terminal is clear in attached picture and I also tried to do it in /root . When I open the directory which must contain packet transaction between android and fb server is empty, just 1 log file. Inside this log file is just URLs requests with time stems.
As it's clear something went wrong in picture 2 it says failed to write: bad file descriptor. I also read sslsplit doc file, but as I'm just entered in Linux couldn't understand with doc file. Please I really need help.

picture 1
http://picpaste.com/1-93rr2eHM.jpeg

picture 2
http://picpaste.com/2-sZhE7gG3.jpeg

**Comment by ranasikandar** [comment] 2015-09-01 12:23
I have been Googling continually, I think it is jail dir issue. and chroot is unknown to me, how can I use sslsplit without jail dir? if jail dir is must how can I jail dir for just sslsplit and undo jail dir changes for my PC.

**Comment by ranasikandar** [comment] 2015-09-01 12:28
I'm sorry for my bad English. (how can I jail dir/chroot for just use this sslsplit and undo jail dir changes from my PC after using sslsplit.)

**Comment by ranasikandar** [comment] 2015-09-03 10:13
it was jail dir. but now problem is that there is so many files of upstream downstream, I just want to filter post data. any clue?

**Comment by droe** [comment] 2015-09-27 14:25
You will need to write scripts to postprocess the POST data collected by sslsplit. Closing the issue since it is not a bug or feature request.

**Closed by droe** 2015-09-27 14:25 UTC
Labels: not-a-bug
