### ISSUE TITLE
Client certificate authentication

### ISSUE THREAD

**Issue by BNET-williamsollers** [droe/sslsplit#173] opened 2017-07-13 22:05 UTC
sslsplit works fine on sites that do not require server side client certs, if they do it can only handle them with the -P (passthrough) option. 

Works when I actually connect to the site and not sslsplit:

curl -k --cert ca.cert.pem --cacert  ca.cert.pem --key key.pem -v https://somesite:8181

Fails when I try to go through sslsplit:

curl -k --cert ca.cert.pem --cacert  ca.cert.pem --key key.pem -v https://localhost:8181

with this error: Error from bufferevent: 0:- 336151570:1042:sslv3 alert bad certificate:20:SSL routines:148:ssl3_read_bytes

packet traces reveal the server is sending a bad certificate error presumably because the client (sslsplit) sent no client cert. The client cert does not appear to be being validated as the certs I am sending are self-signed, but the server is definitely requiring the cert to be there.

It would be nice to be able to specify a default client cert to avoid this. Will look at it.

**Comment by droe** [comment] 2018-01-01 12:53
Feel free to submit a patch adding that feature.

**Comment by droe** [comment] 2018-01-03 22:42
Duplicate of #46, closing this issue, thanks for your report.

**Closed by droe** 2018-01-03 22:42 UTC
Labels: duplicate, feature

**Comment by droe** [comment] 2018-06-03 15:30
Solved by #194.
