### ISSUE TITLE
Can we modify sslsplit to socks5 proxy?

### ISSUE THREAD

**Issue by david-holonet** [droe/sslsplit#130] opened 2016-04-04 02:04 UTC
I think it will make trivial modification to let sslplit change to socks5 proxy, through creating new engine in nat.c, and get source ip and nat from socks5 head.
My issue is I don't know where to add socks5 head for each response session.

**Comment by droe** [comment] 2016-04-04 09:43
Duplicate of #94, closing this ticket, please move discussion there.

**Closed by droe** 2016-04-04 09:43 UTC
