### ISSUE TITLE
Cannot run due to evdns errors (failed to open resolv.conf) with new privsep code

### ISSUE THREAD

**Issue by tokred** [droe/sslsplit#104] opened 2015-07-21 16:33 UTC
Hi there,

I was eager to test the STARTTLS ability of the feature/autossl branch. Unfortunately, I cannot get it to run, neither on Mac OS X nor on Linux:

Issued command: `sudo ./sslsplit -D -l conn.log -j ./out -S ./out/logs -k ca.key -c ca.crt ssl 127.0.0.1 8443 tcp 127.0.0.1 8080`

```
...
NAT engine preinit 'pf'
Created self-pipe [r=6,w=7]
Created chld-pipe [r=8,w=9]
Created socketpair 0 [p=10,c=11]
Created socketpair 1 [p=12,c=13]
Created socketpair 2 [p=14,c=15]
NAT engine fini 'pf'
NAT engine init 'pf'
Received privsep req type 00 sz 1 on srvsock 14
evdns cannot parse resolv.conf: failed to open file (1)
Failed to initialize proxy.
NAT engine fini 'pf'
Received privsep req type 00 sz 1 on srvsock 12
Child proc 1108 exited with status 0
```

On Linux, I get `Error creating dns event base` at the same stage.

Of course, /etc/resolv.conf is available on both systems. On OS X it's actually a soft link to /var/run/resolv.conf but using a regular file does not change anything. sslsplit ran as root with sudo.

What shall I provide to debug this issue?

Thanks and best regards

**Comment by droe** [comment] 2015-07-28 22:21
Can you retry with the latest `develop` branch? I suspect this problem has nothing to do with the commits in `feature/autossl` but rather a side-effect of c01ace1.

Does `make test` yield any failed tests?
What versions of libevent are you using on OS X and on Linux, respectively?
Can user `nobody` access `/etc/resolv.conf` on both systems?

Last resort: In `main.c` there are `#if 0` and `#if 1` around the invocation of `proxy_new()` - does it work for you if you change the 0 to a 1 and vice-versa, that is, if proxy gets created before dropping privileges?

Actually, the dnsbase check could probably be removed if no sni is used, this needs some more work.

**Comment by tokred** [comment] 2015-07-30 12:06
Hi droe, thanks for the response. I switched to `develop`, unfortunately still the same error as above on OS X. I still have to test it on the Linux machine though.

`make test` is fine: `100%: Checks: 129, Failures: 0, Errors: 0`

On OS X, I use libevent 2.0.22 from Homebrew. On Linux, it's 2.0.21.

`resolv.conf` is `-rw-r--r-- 1 root daemon` and therefore accessible by nobody. However, at least on OS X it's a symlink to `/var/run/resolv.conf` (same format though).

**But:** Your proposed last resort worked! After switching the two `#if` in `main.c`, sslsplit starts up just fine.

Thank you very much!

**Comment by droe** [comment] 2015-09-27 14:51
The previous commit does not fix the issue you are seeing, but avoids DNS subsystem initialization for configurations that don't contain any proxy specs which depend on DNS lookups (currently only SNI proxy specs need DNS). Leaving the ticket open, I still plan to look into the actual root cause.

**Comment by freman** [comment] 2015-12-08 22:00
Just tossing my two cents in.

Had the same issue, same thing fixed it.

I checked permissions and even tried `mkdir jail/etc; cp /etc/resolv.conf jail/etc/` it wasn't until I swapped those if's around could I get it working.

**Comment by droe** [comment] 2016-03-15 19:03
Closing this issue. Note that the fix to this issue reverts the workaround for #110 which is not needed anymore with revent libevent versions.

**Closed by droe** 2016-03-15 19:03 UTC
Labels: bug
