### ISSUE TITLE
No Shared Cipher with 0.4.11

### ISSUE THREAD

**Issue by noelsmith** [droe/sslsplit#88] opened 2015-04-20 15:08 UTC
I am receiving the "no shared cipher" error message running the latest version of SSLSplit, compiled with the latest version of OpenSSL.  I tried the "-r tls12" flag but keep getting the same error.  My SSLSplit log is below:

    Generated RSA key for leaf certs.
    SSLsplit master (built 2015-04-09)
    Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
    http://www.roe.ch/SSLsplit
    Build info: V:DIR
    Features: -DHAVE_NETFILTER
    NAT engines: netfilter* tproxy
    netfilter: IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
    Local process info support: no
    compiled against OpenSSL 1.0.2a 19 Mar 2015 (1000201f)
    rtlinked against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
    TLS Server Name Indication (SNI) supported
    OpenSSL is thread-safe with THREADID
    Using SSL_MODE_RELEASE_BUFFERS
    SSL/TLS protocol availability: ssl3 tls10 tls11 tls12 
    SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
    OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET    
    SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION 
    SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS  
    SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
    compiled against libevent 2.0.22-stable
    rtlinked against libevent 2.0.19-stable
    2 CPU cores detected
    SSL/TLS protocol: negotiate
    proxyspecs:
    - [0.0.0.0]:8443 ssl http netfilter
    Loaded CA: '/C=US/ST=NY/L=New York/O=Internet Widgits Pty Ltd/CN=SIFT'
    Using libevent backend 'epoll'
    Event base supports: edge yes, O(1) yes, anyfd no
    Inserted events:
    0x82a1ec8 [fd 7] Read Persist
    0x82a3c94 [fd 8] Read Persist
    0x82a1db8 [fd 6] Read Persist
    0x82a3ce0 [fd 3] Signal Persist
    0x82a3fe0 [fd 1] Signal Persist
    0x82a40c0 [fd 2] Signal Persist
    0x82a41a0 [fd 13] Signal Persist
    Initialized 4 connection handling threads
    Started 4 connection handling threads
    Starting main event loop.
    SNI peek: [REDACTED] [complete]
    Connecting to [54.88.41.174]:443
    ===> Original server certificate:
    Subject DN: /C=US/ST=Virginia/L=Chantilly/O=Excivity, Inc./CN=*.excivity.com
    Common Names: *.excivity.com/*.excivity.com/excivity.com
    Fingerprint: 0e:0b:cd:be:b0:09:e0:50:94:40:c2:31:12:ee:de:a8:3a:38:24:18
    Certificate cache: MISS
    ===> Forged server certificate:
    Subject DN: /C=US/ST=Virginia/L=Chantilly/O=Excivity, Inc./CN=*.excivity.com
    Common Names: *.excivity.com/*.excivity.com/excivity.com
    Fingerprint: 21:57:02:80:bf:7b:0d:8a:fb:b6:10:d3:eb:52:18:91:74:3d:1f:16
    SSL connected to [54.88.41.174]:443 TLSv1.2 ECDHE-RSA-AES256-SHA
    Certificate cache: KEEP (SNI match or target mode)
    Error from bufferevent: 0:- 336109761:193:no shared cipher:20:SSL    
    routines:138:SSL3_GET_CLIENT_HELLO
    SSL disconnected to [54.88.41.174]:443
    SSL disconnected from [10.0.0.1]:33081
    SSL_free() in state 00002112 = SSL_ST_ACCEPT|0112 = 3RCH_C (SSLv3 read client hello C)   
    [accept socket]
    SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect  
    socket]
    ^CReceived signal 2
    Main event loop stopped.

SHA1 of my NEWS.md file is below:

    7e53757ab30b1f43b322a8365d48634a1907bc8e

**Comment by noelsmith** [comment] 2015-04-20 15:17
@droe thanks for your response on Issue 30.  Per your comment I created this issue and included the SHA1 of my NEWS.md file.  Thanks again for your attention.

**Comment by droe** [comment] 2015-04-21 10:13
FTR: You are using SSLsplit 0.4.11 release.

**Comment by droe** [comment] 2015-04-21 10:21
I cannot reproduce the problem with the same version of SSLsplit and OpenSSL 1.0.2. However, you seem to have a library mismatch on your system. You built SSLsplit against OpenSSL 1.0.2, but run it with OpenSSL 1.0.1:

    compiled against OpenSSL 1.0.2a 19 Mar 2015 (1000201f)
    rtlinked against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)

You don't want to do that, especially not across different release branches of OpenSSL. Can you retry with building and running SSLsplit against the same release branch of OpenSSL?

**Comment by noelsmith** [comment] 2015-04-21 14:06
sure, i will try rebuilding SSLsplit to make sure the version i build with matches the version i am running.  i'll report back when finished.  i appreciate your help.

**Comment by droe** [comment] 2015-06-23 17:09
Closing this issue. If the problem turns out to be unrelated to the version mismatch, please reopen it.

**Closed by droe** 2015-06-23 17:09 UTC
Labels: feedback-needed
