### ISSUE TITLE
SSLsplit forwarding traffic to localhost instead of remote host

### ISSUE THREAD

**Issue by cgilmore96** [droe/sslsplit#125] opened 2016-03-16 15:14 UTC
Hello. Thanks in advance for taking time to review my issue, which is almost certainly not a defect in the product but a difficulty I have with configuration. I am attempting to set up an SSLsplit proxy. I'm generally following the advice found at:

https://blog.heckel.xyz/2013/08/04/use-sslsplit-to-transparently-sniff-tls-ssl-connections/

Traffic passes through SSLsplit as expected but then forwards to localhost, similar to how Tyndyll describes his problem in the comments to the blog post.

When I explicitly name a remote host, sslsplit forwards the traffic appropriately, but that locks me into sslsplit only serving as a proxy to that one host.

    $ sudo sysctl -w net.ipv4.ip_forward=1
    $ sudo iptables -t nat -F
    $ sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
    $ sudo iptables -t nat -A PREROUTING -p tcp --dport 636 -j REDIRECT --to-ports 8636
    $ sudo iptables -t nat -A PREROUTING -p tcp --dport 389 -j REDIRECT --to-ports 8389
    $ sudo /usr/local/bin/sslsplit -D -l /home/sslsplit/logs/connections.log -j /home/sslsplit/ -S logs/ -k /home/sslsplit/keystore/sslsplit-ca.key -c /home/sslsplit/keystore/sslsplit-ca.crt tcp 0.0.0.0 8389 ssl 0.0.0.0 8443 ssl 0.0.0.0 8636 > /home/sslsplit/logs/commandline.log 2>&1 &

From connections.log:

    2016-03-15 23:55:21 UTC ssl [9.48.84.122]:61085 [10.108.168.20]:443 sni:www.google.com names:*.podc.sl.edst.ibm.com/*.podc.sl.edst.ibm.com/www.google.com sproto:TLSv1.2:AES256-GCM-SHA384 dproto:TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384

Also:

    $ sslsplit -E
    netfilter (default)
    tproxy

**Comment by droe** [comment] 2016-03-16 22:34
I would need the relevant parts of the debug log, and the output of sslsplit -V, to further diagnose your issue.

**Comment by cgilmore96** [comment] 2016-03-17 00:01
Thank you for taking a look. Please let me know how else I can help!

Thanks,
Christian

[sslsplit@extbasicsslsplit01 logs]$ sslsplit -V
SSLsplit 0.4.11 (built 2016-02-15)
Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Build info: V:FILE
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
rtlinked against OpenSSL 1.0.1e-fips 11 Feb 2013 (1000105f)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
Using direct access workaround when loading certs
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.22-stable
rtlinked against libevent 2.0.21-stable
2 CPU cores detected



[20160316T235509Z-9.48.84.122_52716-10.108.168.20_443.txt](https://github.com/droe/sslsplit/files/177079/20160316T235509Z-9.48.84.122_52716-10.108.168.20_443.txt)
[commandline.txt](https://github.com/droe/sslsplit/files/177077/commandline.txt)
[connections.txt](https://github.com/droe/sslsplit/files/177078/connections.txt)

**Comment by cgilmore96** [comment] 2016-03-22 19:57
Have you had a chance to review the additional information? Thanks!

**Comment by droe** [comment] 2016-03-25 10:26
Where does the internal RFC1918 IP address `10.108.168.20` and the certificate on the CN `*.podc.sl.edst.ibm.com` come from? Is that the local IP address and certificate of the system you are running `sslsplit` on, or perhaps some kind of captive portal?

**Comment by droe** [comment] 2016-03-25 10:29
Also: When you run `ping www.google.com` on `9.48.84.122` (the client), does it resolve www.google.com to the same IP address within `10.0.0.0/8` as `sslsplit` connects to?

**Comment by droe** [comment] 2016-03-25 10:32
And a last thought: You don't by any chance run a Google cache within your corporate network? Can you test with different websites, especially smaller sites not hosted on a global CDN? Do you see the same behaviour for all sites?

**Comment by droe** [comment] 2016-04-07 12:06
Assuming not a bug in SSLsplit and closing issue. Feel free to follow up if you have more information (answers to the above questions, network capture, etc).

**Closed by droe** 2016-04-07 12:06 UTC
Labels: feedback-needed, not-a-bug

**Comment by martin-podlubny** [comment] 2016-06-17 15:53
I think I've hit the same issue, so I might be able to provide any further info needed: But just in case it isn't the same, here's my writeup of I've done and what my problem is... Using www.ssllabs.com as a host for demostration purposes:

**Setup:**

On the client, I got `/etc/hosts` entry of 
```
192.168.1.5 www.ssllabs.com
```

On the server running at `192.168.1.5` I got:
```
$ sysctl -w net.ipv4.ip_forward=1
$ iptables -t nat -F
$ iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
```
**What works:**

````
$ sslsplit -D -k ca.key -c ca.crt ssl 0.0.0.0 8443 www.ssllabs.com 443
```
and visit https://www.ssllabs.com from the client, everything works as expected, I see the SSL cert forging in the STDOUT of sslsplit, and the client browser gets served my self-signed `ca.crt`. sslsplit's STDOUT says
```
SNI peek: [www.ssllabs.com] [complete]
Connecting to [64.41.200.100]:443
===> Original server certificate:
...
```

**What doesn't work:**
````
$ sslsplit -D -k ca.key -c ca.crt ssl 0.0.0.0 8443
```
and visit https://www.ssllabs.com from the client, client browser (Chrome) dies with `ERR_SSL_PROTOCOL_ERROR`. And the STDOUT of sslsplit just says
```
SNI peek: [www.ssllabs.com] [complete]
Connecting to [192.168.1.5]:443
Error from bufferevent: 111:Connection refused 0:0:-:0:-:0:-
SSL disconnected to [(null)]:(null)
SSL disconnected from [192.168.1.10]:51122
SSL_free() in state 00001211 = SSL_ST_CONNECT|0211 = 23WCHB (SSLv2/v3 write client hello B) [connect socket]
...
```
Which in comparison to the first example in which it works shows that sslsplit ends up forwarding traffic to the IP it is running on, instead of the target host (ssllabs' IP).

**Additional info:**
- Linux kali 4.3.0-kali1-amd64 *#*1 SMP Debian 4.3.3-7kali2 (2016-01-27) x86_64 GNU/Linux
- `$ sslsplit -E` -> `netfilter (default), tproxy`
- [sslsplit-v.txt](https://github.com/droe/sslsplit/files/320823/sslsplit-v.txt)

Please let me know if I'm just misunderstanding stuff (I'm in deep waters here), or if there's actually something wrong with the sslstrip :)

**Comment by droe** [comment] 2016-06-18 00:11
That is actually expected behaviour. From the point of view of the server sslsplit is running on, the connection is made to 192.168.1.5, so that is where the upstream connection is made to. sslsplit needs some way to know where you connect to. You can combine sni mode on the server with /etc/hosts on the client, but you cannot combine NAT engine modes with /etc/hosts.

**Comment by stevejohn82** [comment] 2017-03-24 10:58
@droe can you please tell me how to run sslsplit on a Captive portal, as i am confused to set the iptable rules , one for captive portal and one for the sslsplit
