### ISSUE TITLE
Using SSLsplit to feed decrypted data to IDS

### ISSUE THREAD

**Issue by ghostop14** [droe/sslsplit#101] opened 2015-06-30 21:52 UTC
Hi folks,
I'm trying to find a way staying open source to get SSL traffic transparently over to an IDS.  I have commercial solutions that can do similar SSL intercept but they can get expensive.  Is there a way with SSLSplit to have it send the decrypted packet say out to a specified mac address?  I'm thinking if I had a system running sslsplit and another system running something like security onion if I could tell SSLSplit to duplicate all packets unencrypted to a mac address (so security onion would need to be on an attached network) I could then inspect the encrypted traffic.  Any suggestions?

**Comment by droe** [comment] 2015-07-01 19:13
The problem is that SSLsplit decrypts streams or HTTP conversations, not packets (cf #27).

Your best bet is to write a script to parse the SSLsplit logs and replay/simulate the conversations over plain TCP instead of SSL across a virtual network interface for your IDS to listen on. Depending on your IDS there may be other options to get data into the IDS. If you do write such a script, please consider contributing it back into the SSLsplit distribution.

**Comment by droe** [comment] 2015-09-28 11:26
Marking this a duplicate of #27.

**Closed by droe** 2015-09-28 11:26 UTC
Labels: duplicate
