### ISSUE TITLE
sslsplit to sniffer windows update

### ISSUE THREAD

**Issue by leon-pku** [droe/sslsplit#105] opened 2015-08-19 09:13 UTC
I use sslsplit to sniffer windows update 
Windows update return  0x80096004

log as follows:

===> Original server certificate:
Subject DN: /C=US/ST=Washington/L=Redmond/O=Microsoft/OU=DSP/CN=sls.update.microsoft.com
Common Names: sls.update.microsoft.com
Fingerprint: 57:93:77:3c:e5:f9:15:09:5c:57:14:fd:2f:a7:6d:61:49:86:3d:77
Certificate cache: HIT
===> Forged server certificate:
Subject DN: /C=US/ST=Washington/L=Redmond/O=Microsoft/OU=DSP/CN=sls.update.microsoft.com
Common Names: sls.update.microsoft.com/sls.update.microsoft.com
Fingerprint: a4:6d:9a:e1:14:f7:6e:85:7f:d7:20:f8:30:81:ff:10:7d:26:91:f0
SSL connected to [157.56.77.138]:443 TLSv1.2 AES128-SHA256
Certificate cache: KEEP (SNI match or target mode)
SSL connected from [172.168.1.240]:51529 TLSv1.2 AES256-GCM-SHA384
SNI peek: [v10.vortex-win.data.microsoft.com] [complete]

Attempt reuse dst SSL session
Connecting to [111.221.29.254]:443
===> Original server certificate:
Subject DN: /C=US/ST=WA/L=Redmond/O=Microsoft/OU=WSE/CN=*.vortex-win.data.microsoft.com
Common Names: *.vortex-win.data.microsoft.com/*.vortex-win.data.microsoft.com/vortex-win.data.microsoft.com
Fingerprint: 72:85:0a:50:66:7f:e7:3c:28:14:30:e6:f0:2c:5c:2a:24:f3:80:4f
Certificate cache: HIT
===> Forged server certificate:
Subject DN: /C=US/ST=WA/L=Redmond/O=Microsoft/OU=WSE/CN=*.vortex-win.data.microsoft.com
Common Names: *.vortex-win.data.microsoft.com/*.vortex-win.data.microsoft.com/vortex-win.data.microsoft.com
Fingerprint: 76:7c:bd:57:c4:7c:f7:00:69:c5:cc:99:95:7e:0b:c4:23:86:14:f1
SSL connected to [111.221.29.254]:443 TLSv1.2 ECDHE-RSA-AES256-SHA384
Certificate cache: KEEP (SNI match or target mode)
SSL connected from [172.168.1.240]:51532 TLSv1.2 AES256-GCM-SHA384
Unclean SSL shutdown.

any idea why update failed?

**Comment by droe** [comment] 2016-03-15 20:21
If you are using an older version of SSLsplit, this is likely caused by using deprecated algorithms in the forged certificates. What version are you using? Please post the output of `sslsplit -V`

**Comment by droe** [comment] 2016-03-25 23:28
Assuming this is fixed in develop.

**Closed by droe** 2016-03-25 23:28 UTC
Labels: feedback-needed, question

**Comment by droe** [comment] 2016-07-29 19:10
This video seems to solve the issue on the Windows update client side:
https://www.youtube.com/watch?v=EyDaTkU2sKY

Note that latest sslsplit releases use the same hash algorithm as the original upstream certificate.
