### ISSUE TITLE
Error from bufferevent: 111:Connection refused 

### ISSUE THREAD

**Issue by www-upl** [droe/sslsplit#120] opened 2016-01-28 10:42 UTC
I currently get the following error for one domain
```
SNI peek: [www.domain.com] [complete]
Connecting to [173.252.120.68]:443
Error from bufferevent: 111:Connection refused 0:0:-:0:-:0:-

```
when running
```
./sslsplit -k ca.key -c ca.crt ssl 0.0.0.0 8443 sni 443 tcp 0.0.0.0 8080
```
On the "victim" machine, I did a port-forwarding like this
```
iptables -t nat -A OUTPUT -p tcp --dport 443 -j DNAT --to-destination 192.168.0.2:443
```
and open a browser requesting https://www.domain.com

I"ve also tried latest develop branch. But the issue remains.
Could it be, that there is a problem in "pxy_fd_readcb()" or so, that it got a wrong/old ip-address somehow?
I can actually connect doing
`
openssl s_client -connect domain.com:443
`
Any idea how I could further track down the problem?

**Comment by droe** [comment] 2016-03-14 10:46
I don't think that there is such a but that you suspect. Did you compare IP addresses? Did you check with tcpdump or whireshark which connection causes the connection refused?

If all fails: Can you send me the full (unredacted) log to my private e-mail address in case you don't want to publically post it? daniel at roe dot ch.

**Comment by droe** [comment] 2016-03-25 23:31
Looking at this again, the iptables rule above looks bogus. Closing the issue, assuming it is not a bug. If you believe otherwise, please re-open or comment here with more detailed architectural information (all involved systems, their IP addresses and Netfilter (iptables) rules, etc).

**Closed by droe** 2016-03-25 23:31 UTC
Labels: feedback-needed
